server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #设置serverTimezone=GMT%2B8属性,否则数据库存在八小时时差
    url: jdbc:mysql://192.168.64.152:3307/liufeng?Unicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: liufeng

mybatis:
  #指定mybatis配置文件,mybatis-config.xml放在resources可以不指定,该位置为读取的默认路径(该处只是为了说明才定义的)
  config-location: classpath:mybatis-config.xml
  #mybatis配置文件不支持模糊匹配,只能在此配置
  mapperLocations: classpath:mapper/**/*.xml

logging:
  #指定logging配置文件,logback-spring.xml放在resources可以不指定,该位置为读取的默认路径(该处只是为了说明才定义的)
  config: classpath:logback-spring.xml
